/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tubesbasdat;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

/**
 *
 * @author Nata
 */
public class menuOrderAula extends javax.swing.JFrame {
int dragxmouse;
int dragymouse;
    /**
     * Creates new form menuOrderAula
     */
    public menuOrderAula() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jam = new javax.swing.JComboBox<>();
        tanggal = new javax.swing.JTextField();
        jTextFieldID = new javax.swing.JTextField();
        IDPINJAM = new javax.swing.JTextField();
        aulaa = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        NAMA = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(900, 700));
        setMinimumSize(new java.awt.Dimension(900, 700));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(900, 700));
        getContentPane().setLayout(null);

        jLabel3.setFont(new java.awt.Font("Cambria Math", 1, 36)); // NOI18N
        jLabel3.setText("Nama");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(50, 450, 110, 40);

        jLabel4.setFont(new java.awt.Font("Cambria Math", 1, 24)); // NOI18N
        jLabel4.setText("ID PINJAM");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(40, 350, 120, 40);

        jLabel5.setFont(new java.awt.Font("Cambria Math", 1, 24)); // NOI18N
        jLabel5.setText("ID USER");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(50, 240, 100, 50);

        jLabel6.setFont(new java.awt.Font("Cambria Math", 1, 24)); // NOI18N
        jLabel6.setText("JAM");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(620, 340, 70, 50);

        jLabel7.setFont(new java.awt.Font("Cambria Math", 1, 24)); // NOI18N
        jLabel7.setText("Aula");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(620, 240, 70, 50);

        jam.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih", "07.00 - 09.00", "09.15 - 11.15", "13.00 - 15.00", "16.30 - 18.00" }));
        getContentPane().add(jam);
        jam.setBounds(740, 340, 130, 50);

        tanggal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tanggalActionPerformed(evt);
            }
        });
        getContentPane().add(tanggal);
        tanggal.setBounds(200, 530, 200, 50);
        getContentPane().add(jTextFieldID);
        jTextFieldID.setBounds(200, 240, 200, 50);
        getContentPane().add(IDPINJAM);
        IDPINJAM.setBounds(200, 340, 200, 50);

        aulaa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih", "AUL01", "AUL02", "AUL03", " ", " " }));
        aulaa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aulaaActionPerformed(evt);
            }
        });
        getContentPane().add(aulaa);
        aulaa.setBounds(740, 240, 130, 50);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tubes/basdat/images/Button-Remove-iconss.png"))); // NOI18N
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel8);
        jLabel8.setBounds(850, 10, 40, 40);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tubes/basdat/images/Button-Previous-icon.png"))); // NOI18N
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel9);
        jLabel9.setBounds(450, 650, 60, 40);

        jButton1.setText("PESAN");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(410, 600, 110, 40);

        jPanel1.setBackground(new java.awt.Color(58, 209, 242));
        jPanel1.setForeground(new java.awt.Color(96, 211, 246));

        jLabel10.setFont(new java.awt.Font("Calibri", 1, 30)); // NOI18N
        jLabel10.setText("Tanggal");
        jPanel1.add(jLabel10);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(40, 530, 130, 50);

        NAMA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NAMAActionPerformed(evt);
            }
        });
        getContentPane().add(NAMA);
        NAMA.setBounds(200, 440, 200, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tubes/basdat/images/menuOrderAula.jpg"))); // NOI18N
        jLabel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel1MouseDragged(evt);
            }
        });
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel1MousePressed(evt);
            }
        });
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 900, 700);

        setSize(new java.awt.Dimension(900, 700));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tanggalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tanggalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tanggalActionPerformed

    private void jLabel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        
        this.setLocation(x - dragxmouse, y - dragymouse);
        System.out.println(x+"," +y);
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1MouseDragged

    private void jLabel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MousePressed
       dragxmouse = evt.getX();
        dragymouse = evt.getY();
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1MousePressed

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        new menuUserOrder().setVisible(true);
        setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String iduser=jTextFieldID.getText();
        String  idpinjam = IDPINJAM.getText();
        String name =NAMA.getText();
        String tgl = tanggal.getText();
        String aul = aulaa.getSelectedItem().toString();
        String jamm = jam.getSelectedItem().toString(); 
        
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/basisdata","root","");
            String query ="INSERT INTO peminjaman (id_user,id_pinjam, nama,tgl_pinjam,kd_ruang, jam_pinjam) values (?,?,?,?,?,?)";
            
            PreparedStatement ps= con.prepareStatement(query);
            ps.setString(1, iduser);
            ps.setString(2, idpinjam);
            ps.setString(3, name);
            ps.setString(4,tgl);
            ps.setString(5,aul);
            ps.setString(6, jamm);
            
             ps.executeUpdate();
        JOptionPane.showMessageDialog(null, "Peminjaman Berhasil ");
        }catch(Exception ex){
             System.out.println(ex.getMessage());    
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void aulaaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aulaaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aulaaActionPerformed

    private void NAMAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NAMAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NAMAActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
     
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menuOrderAula().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField IDPINJAM;
    private javax.swing.JTextField NAMA;
    private javax.swing.JComboBox<String> aulaa;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldID;
    private javax.swing.JComboBox<String> jam;
    private javax.swing.JTextField tanggal;
    // End of variables declaration//GEN-END:variables
}
