/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tubespbo;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Nata
 */
public class menuConfirm extends javax.swing.JFrame {
int dragxmouse;
int dragymouse;
    /**
     * Creates new form menuConfirm
     */
    public menuConfirm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldConfirmAdmin1 = new javax.swing.JTextField();
        jPasswordFieldAdmin = new javax.swing.JPasswordField();
        jButtonLoginConfirm = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(500, 500));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(500, 500));
        getContentPane().setLayout(null);
        getContentPane().add(jTextFieldConfirmAdmin1);
        jTextFieldConfirmAdmin1.setBounds(90, 160, 300, 40);
        getContentPane().add(jPasswordFieldAdmin);
        jPasswordFieldAdmin.setBounds(90, 260, 300, 40);

        jButtonLoginConfirm.setText("Login");
        jButtonLoginConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoginConfirmActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonLoginConfirm);
        jButtonLoginConfirm.setBounds(220, 320, 79, 25);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tubespbo/images/Button-Remove-iconss_1.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2);
        jLabel2.setBounds(450, 10, 40, 40);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih", "Admin" }));
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(380, 120, 64, 22);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tubespbo/images/menuConfirm.jpg"))); // NOI18N
        jLabel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel1MouseDragged(evt);
            }
        });
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel1MousePressed(evt);
            }
        });
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 500, 500);

        setSize(new java.awt.Dimension(500, 500));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseDragged
        // TODO add your handling code here:
         int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        
        this.setLocation(x - dragxmouse, y - dragymouse);
        System.out.println(x+"," +y);
    }//GEN-LAST:event_jLabel1MouseDragged

    private void jLabel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MousePressed
        // TODO add your handling code here:
        dragxmouse = evt.getX();
        dragymouse = evt.getY();
    }//GEN-LAST:event_jLabel1MousePressed

    private void jButtonLoginConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoginConfirmActionPerformed
        String uname = jTextFieldConfirmAdmin1.getText();
        String pass = jPasswordFieldAdmin.getText();
        String level = jComboBox1.getSelectedItem().toString();
        
        try{
            Connection con = MyConnection.getConnection();
          
            ResultSet rs;
            PreparedStatement ps;
  
             ps= con.prepareStatement("SELECT * FROM user WHERE username=? AND password=? ");
                ps.setString(1, uname);
                ps.setString(2, pass);
                rs=ps.executeQuery();
                
                if (rs.next()){
                    String password = rs.getString("password");
                    String s1 = rs.getString("level");
                         if(level.equalsIgnoreCase("admin") && s1.equalsIgnoreCase("admin") ){
                              dispose(); 
                             JOptionPane.showMessageDialog(null,"Admin Confirm");
                             new menuReset().setVisible(true);
                        }else{
                             JOptionPane.showMessageDialog(null,"You Not Valid Admin ! !");
                              dispose(); 
                              
                        }
                }
                
            
        }catch(Exception ex){
              System.out.println(""+ex); 
        }
    }//GEN-LAST:event_jButtonLoginConfirmActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuConfirm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuConfirm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuConfirm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuConfirm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menuConfirm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonLoginConfirm;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPasswordField jPasswordFieldAdmin;
    private javax.swing.JTextField jTextFieldConfirmAdmin1;
    // End of variables declaration//GEN-END:variables
}
